Fix landing page
HarryET/custodi pull request #37
Opened 2021-12-10 02:27 UTC by Isaiah-Hamilton

2021-12-10 06:53 UTC, HarryET requested changes, later dismissed
Can we use an SVG insted of a jpg?

2021-12-11 03:04 UTC, Isaiah-Hamilton commented
> Can we use an SVG insted of a jpg?

Were is the `jpg` file or which file are you talking about?

2021-12-11 21:54 UTC, HarryET commented
> > Can we use an SVG insted of a jpg?
> 
> @HarryET Were is the `jpg` file or which file are you talking about?

I think it was removed in code but the file still exists public/assets/product-demo-img.jpg

2021-12-12 03:39 UTC, VictorPeralta approved these changes

2021-12-12 03:50 UTC, merged